### ISSUE TITLE
Pin location changes on zoom in/zoom out

### ISSUE THREAD

**Issue by PawelZarzycki** [suchoX/PlacePicker#19]
Hey,
When the user tries to zoom in/ zoom out, the location of the pin changes. This surely shouldn't happen and is not as any other map application. Are you aware of this issue?

**Comment by suchoX** [comment]
@PawelZarzycki, when you are zooming in/out the location of the pin, the location may change. If you are completely zoomed out and place your pin on California and completely zoom in to San Francisco, The location technically doesn't change, but the address does. Hence this is a place picker where the address is important, I chose this approach. It's expected behaviour. Closing this issue as of now. Re-open it if you need
